version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: voting-postgres
    environment:
      POSTGRES_DB: votingdb
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voting -d votingdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: voting-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-web
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis


volumes:
  postgres_data:
  redis_data: