version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: voting-postgres
    environment:
      POSTGRES_DB: votingdb
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secret -d votingdb"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
  redis_data: