CREATE TABLE agenda (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    des_title         VARCHAR(500) NOT NULL,
    result            VARCHAR(500),
    dat_create_result TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
