CREATE TABLE voting_session (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id  BIGINT NOT NULL,
    starts_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_voting_session_agenda FOREIGN KEY (agenda_id) REFERENCES agenda(id),
    CONSTRAINT uk_voting_session_agenda UNIQUE (agenda_id)
);
