CREATE TABLE vote (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_session_id  BIGINT NOT NULL,
    associate_id       UUID NOT NULL,
    des_vote           BOOLEAN NOT NULL,
    dat_created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_voting_session FOREIGN KEY (voting_session_id) REFERENCES voting_session(id),
    CONSTRAINT fk_vote_associate FOREIGN KEY (associate_id) REFERENCES associate(id),
    CONSTRAINT uq_vote_voting_session_associate UNIQUE (voting_session_id, associate_id)
);
