-- Execute SQL script
-- ====================================================================================================
-- TABLE: agenda (pauta)
-- ====================================================================================================
CREATE TABLE agenda (
                        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        des_title         VARCHAR(500) NOT NULL,
                        result            VARCHAR(500),
                        dat_create_result TIMESTAMPTZ,
                        created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agenda IS
'Voting agenda item. Has at most one associated voting session (enforced by voting_session.agenda_id UNIQUE). The result is only filled after the session ends.';

COMMENT ON COLUMN agenda.id IS
'Unique agenda identifier (PK). Auto-generated (IDENTITY).';

COMMENT ON COLUMN agenda.des_title IS
'Agenda title/description. Required.';

COMMENT ON COLUMN agenda.result IS
'Final voting result snapshot. Must remain NULL while the session is open (no preview allowed).';

COMMENT ON COLUMN agenda.dat_create_result IS
'Timestamp when the final result was computed/persisted. Must be set only when the session is closed.';

COMMENT ON COLUMN agenda.created_at IS
'Agenda creation timestamp (default: now()).';

