-- ====================================================================================================
-- TABLE: voting_session
-- ====================================================================================================
CREATE TABLE voting_session (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                agenda_id  BIGINT NOT NULL,
                                start_at   TIMESTAMPTZ NOT NULL,
                                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                CONSTRAINT fk_voting_session_agenda FOREIGN KEY (agenda_id) REFERENCES agenda(id),
                                CONSTRAINT uk_voting_session_agenda UNIQUE (agenda_id)
);

COMMENT ON TABLE voting_session IS
'Voting session associated to an agenda (one-to-one). The session closes at start_at.';

COMMENT ON COLUMN voting_session.id IS
'Unique voting session identifier (PK). Auto-generated (IDENTITY).';

COMMENT ON COLUMN voting_session.agenda_id IS
'Agenda identifier (FK). Unique to ensure one session per agenda.';

COMMENT ON COLUMN voting_session.start_at IS
'Timestamp when the session closes (now + duration).';

COMMENT ON COLUMN voting_session.created_at IS
'Voting session creation timestamp (default: now()).';
