-- ====================================================================================================
-- TABLE: voting_session (sessão)
-- rule: 1 voting_session per agenda (agenda_id UNIQUE)
-- ====================================================================================================
CREATE TABLE voting_session (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                agenda_id  BIGINT NOT NULL UNIQUE,
                                starts_at  TIMESTAMPTZ NOT NULL,
                                ends_at    TIMESTAMPTZ NOT NULL,
                                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

                                CONSTRAINT fk_voting_session_agenda
                                    FOREIGN KEY (agenda_id)
                                        REFERENCES public.agenda(id)
                                        ON UPDATE RESTRICT
                                        ON DELETE RESTRICT
                                        NOT DEFERRABLE
);

ALTER TABLE voting_session VALIDATE CONSTRAINT fk_voting_session_agenda;

COMMENT ON TABLE voting_session IS
'Voting session for a single agenda item (1:1).';

COMMENT ON COLUMN voting_session.id IS
'Unique voting session identifier (PK). Auto-generated (IDENTITY).';

COMMENT ON COLUMN voting_session.agenda_id IS
'Agenda identifier associated with this voting session. Required and UNIQUE (one voting session per agenda).';

COMMENT ON COLUMN voting_session.starts_at IS
'Session start timestamp (inclusive). Voting is allowed only after this instant.';

COMMENT ON COLUMN voting_session.ends_at IS
'Session end timestamp (exclusive). Voting is not allowed at or after this instant.';

COMMENT ON COLUMN voting_session.created_at IS
'Voting session creation timestamp (default: now()).';

COMMENT ON CONSTRAINT fk_voting_session_agenda ON voting_session IS
'Ensures the voting session references an existing agenda item. Deletion of an agenda with an existing session is restricted.';
