
-- ====================================================================================================
-- TABLE: associate (associado)
-- NOTE: requires pgcrypto only if you want DB-generated UUIDs via gen_random_uuid().
-- If pgcrypto is not enabled, generate UUID in the application instead.
-- ====================================================================================================
CREATE TABLE associate (
                           id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                           des_document   VARCHAR(14) NOT NULL,
                           dat_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

                           CONSTRAINT uq_associate_des_document UNIQUE (des_document)
);

COMMENT ON TABLE associate IS
'Represents a cooperative associate (associado).';

COMMENT ON COLUMN associate.id IS
'Primary identifier for the associate (UUID). Generated by the database using gen_random_uuid().';

COMMENT ON COLUMN associate.des_document IS
'Associate document (digits-only CPF/CNPJ). Stored in plaintext by design decision.';

COMMENT ON COLUMN associate.dat_created_at IS
'Timestamp when the associate record was created (timestamptz; UTC recommended).';

COMMENT ON CONSTRAINT uq_associate_des_document ON associate IS
'Ensures the document is unique, preventing multiple associates from being registered with the same CPF/CNPJ.';
