-- ====================================================================================================
-- TABLE: vote (voto)
-- vote is tied to a voting_session
-- ====================================================================================================
CREATE TABLE vote (
                      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                      voting_session_id BIGINT NOT NULL,
                      associate_id      UUID NOT NULL,

                      des_vote       BOOLEAN NOT NULL, -- TRUE = YES (SIM), FALSE = NO (NAO)
                      dat_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

                      CONSTRAINT fk_vote_voting_session
                          FOREIGN KEY (voting_session_id) REFERENCES voting_session(id) ON DELETE RESTRICT,

                      CONSTRAINT fk_vote_associate
                          FOREIGN KEY (associate_id) REFERENCES associate(id) ON DELETE RESTRICT,

                      CONSTRAINT uq_vote_voting_session_associate UNIQUE (voting_session_id, associate_id)
);

COMMENT ON TABLE vote IS
'Stores votes cast by associates during a voting session. Each associate can vote at most once per voting session.';

COMMENT ON COLUMN vote.id IS
'Primary key for the vote record (BIGINT IDENTITY).';

COMMENT ON COLUMN vote.voting_session_id IS
'Reference to the voting session in which the vote was cast.';

COMMENT ON COLUMN vote.associate_id IS
'Reference to the cooperative associate (associado) who cast the vote.';

COMMENT ON COLUMN vote.des_vote IS
'Vote value: TRUE means YES (SIM), FALSE means NO (NAO).';

COMMENT ON COLUMN vote.dat_created_at IS
'Timestamp when the vote was recorded (timestamptz; UTC recommended).';

COMMENT ON CONSTRAINT fk_vote_voting_session ON vote IS
'Ensures votes reference an existing voting session. Deletion is restricted while votes exist.';

COMMENT ON CONSTRAINT fk_vote_associate ON vote IS
'Ensures votes reference an existing associate. Deletion is restricted while votes exist.';

COMMENT ON CONSTRAINT uq_vote_voting_session_associate ON vote IS
'Prevents duplicate votes by the same associate in the same voting session (enforces 1 vote per associate per session).';